import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Image, ImageBackground, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { collection, getDocs } from 'firebase/firestore';
import { db } from '../firebase';
import { useRouter } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';
import FontSizeControl from '../components/FontSizeControl';
import BottomNav from '../components/BottomNav';

const LOCAL_GAZALS = [
  { id: 'local-1', title: 'ইয়া নবী সালাম আলাইকা', description: 'সুন্দর নাতে রাসুল ﷺ', lyrics: 'ইয়া নবী সালাম আলাইকা\nইয়া রাসুল সালাম আলাইকা' },
  { id: 'local-2', title: 'মেরে সরকার আয়ে', description: 'আধ্যাত্মিক গজল', lyrics: 'মেরে সরকার আয়ে, নূর নিয়ে আয়ে\nদিলের অন্ধকার দূর করে আয়ে' },
  { id: 'local-3', title: 'চিশতিয়া কাওয়ালি', description: 'চিশতিয়া দরবার শরীফের গজল', lyrics: 'চিশতিয়ার পথে চলি, ভালোবাসা বুকে তুলি\nখেদমতে জীবন কাটাই' },
];

export default function GazalBook() {
  const router = useRouter(); const [items, setItems] = useState<any[]>([]); const [index, setIndex] = useState(0); const [fontSize, setFontSize] = useState(16); const [loading, setLoading] = useState(true);
  useEffect(() => { (async () => { try { const cache = await AsyncStorage.getItem('@gazals'); if (cache) setItems(JSON.parse(cache)); const q = await getDocs(collection(db, 'gazals')); const fresh = q.docs.map(d => ({ id: d.id, ...d.data() })); const data = fresh.length ? fresh : (cache ? JSON.parse(cache) : LOCAL_GAZALS); setItems(data); await AsyncStorage.setItem('@gazals', JSON.stringify(data)); } catch { const cache = await AsyncStorage.getItem('@gazals'); setItems(cache ? JSON.parse(cache) : LOCAL_GAZALS); } finally { setLoading(false); } })(); }, []);
  const item = items[index];
  return <ImageBackground source={{ uri: 'https://t4.ftcdn.net/jpg/04/24/19/47/360_F_424194700_YLn8PuaiqR36LI84T9E76ATDd6HrU2at.jpg' }} style={s.bg}><ScrollView contentContainerStyle={s.container}><FontSizeControl size={fontSize} onChange={setFontSize}/><TouchableOpacity style={s.back} onPress={() => router.back()}><Text style={s.backText}>← ফিরে যান</Text></TouchableOpacity><View style={s.header}><Text style={s.heading}>গজল ও নাত</Text><Text style={s.sub}>আধ্যাত্মিক গজল সংগ্রহ</Text></View>{loading ? <ActivityIndicator color="#f9bf3a"/> : item ? <View style={s.card}>{item.imageUrl || item.image ? <Image source={{ uri: item.imageUrl || item.image }} style={s.image}/> : null}<Text style={[s.title,{fontSize:fontSize+4}]}>{item.title || item.name || 'গজল'}</Text>{item.author ? <Text style={s.author}>শিল্পী: {item.author}</Text> : null}<Text style={[s.desc,{fontSize,lineHeight:fontSize*1.7}]}>{item.lyrics || item.description || item.content || ''}</Text><View style={s.nav}><TouchableOpacity style={[s.btn,index===0&&s.disabled]} disabled={index===0} onPress={()=>setIndex(index-1)}><Text style={s.btnText}>◀ আগের গজল</Text></TouchableOpacity><Text style={s.count}>{index+1} / {items.length}</Text><TouchableOpacity style={[s.btn,index===items.length-1&&s.disabled]} disabled={index===items.length-1} onPress={()=>setIndex(index+1)}><Text style={s.btnText}>পরের গজল ▶</Text></TouchableOpacity></View></View> : null}</ScrollView><BottomNav activeTab="home"/></ImageBackground>;
}
const s=StyleSheet.create({bg:{flex:1},container:{padding:18,paddingBottom:100},back:{alignSelf:'flex-start',backgroundColor:'#0f562a',padding:9,borderRadius:18,marginBottom:10},backText:{color:'#fff',fontWeight:'700'},header:{backgroundColor:'#0f562a',borderRadius:18,padding:18,alignItems:'center',marginBottom:18},heading:{color:'#f9bf3a',fontSize:26,fontWeight:'800'},sub:{color:'#fff',marginTop:5},card:{backgroundColor:'#fffdf9',borderRadius:16,padding:20,borderWidth:1.5,borderColor:'#d4af37'},image:{width:'100%',height:190,borderRadius:12,marginBottom:15},title:{color:'#0f562a',fontWeight:'900',textAlign:'center',marginBottom:8},author:{color:'#0f562a',textAlign:'center',fontWeight:'700',marginBottom:12},desc:{color:'#303030',textAlign:'center',marginBottom:22},nav:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderTopWidth:1,borderTopColor:'#eee',paddingTop:14},btn:{backgroundColor:'#0f562a',paddingHorizontal:10,paddingVertical:9,borderRadius:8},disabled:{backgroundColor:'#bbb'},btnText:{color:'#fff',fontWeight:'700',fontSize:12},count:{color:'#555',fontWeight:'700'}});
