import React, { useState } from 'react';
import { ImageBackground, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import BottomNav from '../components/BottomNav';

const backgroundImage = { uri: 'https://t4.ftcdn.net/jpg/04/24/19/47/360_F_424194700_YLn8PuaiqR36LI84T9E76ATDd6HrU2at.jpg' };
const prerequisites = ['শরীর ও কাপড় পাক হওয়া: ওজু বা গোসলের মাধ্যমে পবিত্রতা অর্জন এবং পরিষ্কার পোশাক পরিধান।', 'স্থান পাক হওয়া: সেজদা করার জায়গা পবিত্র হওয়া।', 'সতর ঢাকা: পুরুষদের নাভি থেকে হাঁটু পর্যন্ত এবং নারীদের মুখমণ্ডল, দুই হাত ও পায়ের পাতা ছাড়া সমস্ত শরীর ঢেকে রাখা।', 'কিবলামুখী হওয়া: কাবার দিকে মুখ করে দাঁড়ানো।', 'ওয়াক্ত হওয়া: নির্দিষ্ট ওয়াক্তের নামাজ সঠিক সময়ে আদায় করা।', 'নিয়ত করা: যে ওয়াক্তের নামাজ পড়ছেন অন্তরে তার সংকল্প করা।'];
const rakats = [['ফজর', '২', '২', '—', '—', '৪'], ['জোহর', '৪', '৪', '২ সুন্নত + ২ নফল', '—', '১২'], ['আসর', '—', '৪', '—', '—', '৪'], ['মাগরিব', '—', '৩', '২ সুন্নত + ২ নফল', '—', '৭'], ['এশা', '৪', '৪', '২ সুন্নত + ২ নফল', '৩', '১৭']];
const steps = [
  ['নিয়ত ও তাকবিরে তাহরিমা', 'কিবলামুখী হয়ে “আল্লাহু আকবার” বলে হাত উঠিয়ে হাত বাঁধুন।'],
  ['ছানা ও ক্বিরাআত', 'ছানা পাঠ করে আউজু-বিসমিল্লাহ, সূরা ফাতিহা এবং অন্য একটি সূরা পড়ুন।'],
  ['রুকু', '“আল্লাহু আকবার” বলে রুকুতে গিয়ে অন্তত ৩ বার “সুবহানা রব্বিয়াল আজীম” পড়ুন।'],
  ['কাউমা', '“সামিআল্লাহু লিমান হামিদাহ” বলে সোজা হয়ে দাঁড়িয়ে “রব্বানা লাকাল হামদ” বলুন।'],
  ['সেজদা ও জলসা', 'দুটি সেজদা করুন; প্রতিটি সেজদায় অন্তত ৩ বার “সুবহানা রব্বিয়াল আলা” পড়ুন।'],
  ['শেষ বৈঠক ও সালাম', 'তাশাহহুদ, দরুদ শরীফ ও দোআয়ে মাসুরা পড়ে ডানে ও বামে সালাম ফেরান।'],
];
const duas = [['তাশাহহুদ (আত্তাহিয়্যাতু)', 'আত্তাহিয়্যাতু লিল্লাহি ওয়াস সালাওয়াতু ওয়াত তাইয়্যিবাতু, আসসালামু আলাইকা আইয়্যুহান নাবিয়্যু ওয়া রাহমাতুল্লাহি ওয়া বারাকাতুহু, আসসালামু আলাইনা ওয়া আলা ইবাদিল্লাহিস সালিহীন। আশহাদু আল-লা ইলাহা ইল্লাল্লাহু ওয়া আশহাদু আন্না মুহাম্মাদান আবদুহু ওয়া রাসুলুহ।'], ['দরুদ শরীফ', 'আল্লাহুম্মা সাল্লি আলা মুহাম্মাদিও ওয়া আলা আলি মুহাম্মাদ, কামা সাল্লাইতা আলা ইব্রাহিমা ওয়া আলা আলি ইব্রাহিম, ইন্নাকা হামিদুম মাজিদ। আল্লাহুম্মা বারিক আলা মুহাম্মাদিও ওয়া আলা আলি মুহাম্মাদ, কামা বারাক্তা আলা ইব্রাহিমা ওয়া আলা আলি ইব্রাহিম, ইন্নাকা হামিদুম মাজিদ।'], ['দোআয়ে মাসুরা', 'আল্লাহুম্মা ইন্নি জলামতু নাফসি জুলমান কাসিরাও ওয়া লা ইয়াগফিরুজ জুনুবা ইল্লা আনতা, ফাগফিরলি মাগফিরাতাম মিন ইনদিকা ওয়ারহামনি ইন্নাকা আনতাল গাফুরুর রাহিম।']];

export default function NamazShiksha() {
  const router = useRouter(); const [open, setOpen] = useState<number | null>(0);
  const toggle = (i: number) => setOpen(open === i ? null : i);
  return <ImageBackground source={backgroundImage} resizeMode="cover" style={styles.background}><ScrollView contentContainerStyle={styles.container} showsVerticalScrollIndicator={false}>
    <TouchableOpacity style={styles.backButton} onPress={() => router.back()}><Text style={styles.backText}>← Back</Text></TouchableOpacity>
    <View style={styles.header}><Text style={styles.heading}>নামাজ শিক্ষা</Text><Text style={styles.subtitle}>সহজভাবে নামাজ আদায়ের প্রয়োজনীয় নির্দেশনা</Text></View>
    <Section title="১. নামাজের প্রধান পূর্বশর্ত (ফরজসমূহ)" index={0} open={open} toggle={toggle}><View>{prerequisites.map((x, i) => <Text key={i} style={styles.item}>• {x}</Text>)}</View></Section>
    <Section title="২. পাঁচ ওয়াক্ত নামাজের মোট রাকাত" index={1} open={open} toggle={toggle}><View style={styles.table}>{['ওয়াক্ত','সুন্নত','ফরজ','নফল','বিতর','মোট'].map(x => <Text key={x} style={[styles.cell, styles.headCell]}>{x}</Text>)}{rakats.flat().map((x,i) => <Text key={i} style={styles.cell}>{x}</Text>)}</View></Section>
    <Section title="৩. ধাপে ধাপে ২ রাকাত নামাজ" index={2} open={open} toggle={toggle}>{steps.map(([a,b],i)=><View key={i} style={styles.quoteCard}><Text style={styles.label}>{i+1}. {a}</Text><Text style={styles.quote}>{b}</Text></View>)}</Section>
    <Section title="৪. বৈঠকে পঠিত আবশ্যক দোয়া" index={3} open={open} toggle={toggle}>{duas.map(([a,b])=><View key={a} style={styles.quoteCard}><Text style={styles.label}>{a}</Text><Text style={styles.quote}>{b}</Text></View>)}<View style={styles.quoteCard}><Text style={styles.label}>সালাম ফেরানো</Text><Text style={styles.quote}>ডানে ঘাড় ঘুরিয়ে বলুন: “আসসালামু আলাইকুম ওয়া রাহমাতুল্লাহ”।</Text> <Text style={styles.quote}>বামে ঘাড় ঘুরিয়ে বলুন: “আসসালামু আলাইকুম ওয়া রাহমাতুল্লাহ”।</Text></View></Section>
    <View style={styles.note}><Text style={styles.noteText}>নোট: ৩ বা ৪ রাকাত নামাজে ২য় রাকাতে কেবল তাশাহহুদ পড়ে ৩য় রাকাতের জন্য দাঁড়াতে হয় এবং শেষ রাকাতে পূর্ণাঙ্গ বৈঠক করে সালাম ফেরাতে হয়।</Text></View>
  </ScrollView><BottomNav activeTab="home" /></ImageBackground>;
}
function Section({title,index,open,toggle,children}:{title:string;index:number;open:number|null;toggle:(i:number)=>void;children:React.ReactNode}) { return <View style={styles.section}><TouchableOpacity activeOpacity={.85} onPress={()=>toggle(index)}><View style={styles.sectionTitleRow}><Text style={styles.sectionTitle}>{title}</Text><Text style={styles.chevron}>{open===index?'−':'+'}</Text></View></TouchableOpacity>{open===index&&<View style={styles.content}>{children}</View>}</View> }
const styles=StyleSheet.create({background:{flex:1},container:{padding:16,paddingBottom:100},backButton:{alignSelf:'flex-start',backgroundColor:'#0f562a',paddingHorizontal:14,paddingVertical:10,borderRadius:10},backText:{color:'#fff',fontWeight:'700'},header:{marginTop:14,marginBottom:18,backgroundColor:'#0f562a',borderRadius:18,padding:18,alignItems:'center',borderWidth:1,borderColor:'#f9bf3a'},heading:{color:'#f9bf3a',fontSize:28,fontWeight:'800',textAlign:'center'},subtitle:{color:'#eaf7ee',marginTop:5,fontSize:13},section:{marginBottom:14},sectionTitleRow:{flexDirection:'row',alignItems:'center',backgroundColor:'#0f562a',borderRadius:12,paddingHorizontal:14,paddingVertical:12},sectionTitle:{color:'#fff',flex:1,fontSize:17,fontWeight:'800',lineHeight:24},chevron:{color:'#f9bf3a',fontSize:27,fontWeight:'700',marginLeft:8},content:{backgroundColor:'rgba(255,255,255,.96)',padding:12,borderBottomLeftRadius:14,borderBottomRightRadius:14},item:{color:'#303030',fontSize:15,lineHeight:25,marginBottom:5},table:{flexDirection:'row',flexWrap:'wrap',borderWidth:1,borderColor:'#0f562a'},cell:{width:'16.666%',minHeight:42,textAlign:'center',textAlignVertical:'center',padding:4,borderRightWidth:1,borderBottomWidth:1,borderColor:'#b7c8b8',fontSize:12,color:'#303030'},headCell:{backgroundColor:'#0f562a',color:'#fff',fontWeight:'800'},quoteCard:{marginBottom:9,borderLeftWidth:5,borderLeftColor:'#f9bf3a',padding:10,backgroundColor:'#fffdf7',borderRadius:9},label:{color:'#0f562a',fontSize:15,fontWeight:'800',marginBottom:4},quote:{color:'#303030',fontSize:15,lineHeight:24},note:{backgroundColor:'#fff8df',borderRadius:12,padding:14,borderWidth:1,borderColor:'#f9bf3a',marginTop:4},noteText:{color:'#513d00',fontSize:14,lineHeight:23,fontWeight:'600'} });
